import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
  {/* Top Navigation */}
  <header className="p-4 border-b">
    <nav className="flex gap-6 font-medium">
      <a href="/">Home</a>
      <a href="/about">About</a>
      <a href="/services">Services</a>
      <a href="/contact">Contact</a>
    </nav>
  </header>

  {/* Page Content */}
  {children}

  {/* Footer */}
  <footer className="p-6 border-t text-sm text-gray-600">
    <p className="font-medium">
      G.Bro Customs Clearing and Logistic Sewa
    </p>
    <p>Kathmandu, Nepal</p>
    <p>© {new Date().getFullYear()} All rights reserved.</p>
  </footer>
</body>
    </html>
  );
}
